# Generated by Django 5.2.14 on 2026-05-28 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ko",
                    models.CharField(max_length=80, verbose_name="Korean title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=80, verbose_name="English title"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description_ko", models.CharField(blank=True, max_length=180)),
                ("description_en", models.CharField(blank=True, max_length=180)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["order", "title_ko"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ko", "Korean"), ("en", "English")],
                        default="ko",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField()),
                ("summary", models.TextField(max_length=420)),
                ("body", models.TextField()),
                ("featured_image", models.ImageField(blank=True, upload_to="posts/")),
                ("image_alt", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("reading_minutes", models.PositiveSmallIntegerField(default=1)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.category",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translated_versions",
                        to="blog.post",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language", "slug"),
                        name="unique_post_slug_per_language",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("translation", models.F("id")), _negated=True
                        ),
                        name="post_translation_cannot_point_to_self",
                    ),
                ],
            },
        ),
    ]
