# Generated by Django 5.2.14 on 2026-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80)),
                ("tagline_ko", models.CharField(max_length=160)),
                ("tagline_en", models.CharField(max_length=160)),
                ("bio_ko", models.TextField()),
                ("bio_en", models.TextField()),
                ("location_ko", models.CharField(blank=True, max_length=80)),
                ("location_en", models.CharField(blank=True, max_length=80)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("hero_image", models.ImageField(blank=True, upload_to="profile/")),
                ("hero_image_alt", models.CharField(blank=True, max_length=160)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site profile",
                "verbose_name_plural": "site profile",
            },
        ),
    ]
